### ISSUE TITLE
[METERING] Extract JWT in each request and attach to L1 ingestor log submission

### ISSUE THREAD

**Issue by tchardin** [filecoin-saturn/L1-node#494]
were going to break this into two milestones

### milestone 1

* [x] implement authentication based on session token JWTs such that each request gets logged appropriately under the correct customer's account for metering, but not billing, purposes

### milestone 2

* [ ] l1s validate session token JWTs and either accept or reject requests without having to make an external network request 
* [x] arc and gateway (caboose) traffic will need to be authenticated, too 👏 

why break the above into two milestones?
* if we launch at lab week without l1s validating session JWTs, effectively all bandwidth is free and there's no reason for customers to pay us or select a plan beyond the free plan. however, this is acceptable and preferable to not launching at all if we don't have time to also implement milestone 2
* ideally, we launch with both milestone 1 and milestone 2, where with milestone 2 customers will have to pay once they hit their plan's cap (or pay us as part of the pay-as-you-go plan)

**Comment by guanzo** [comment]
> arc and gateway (caboose) traffic will need to be authenticated, too

Does this mean that all requests will become authenticated in the future? So you can't simply `curl` an L1 anymore?

**Comment by guanzo** [comment]
JWTs are being extracted from nginx access logs and submitted to the log-ingestor which stores it into postgres.

**Comment by wilkyr31d** [comment]
@guanzo I'm super assuming this can be closed now, but if I'm wrong re-open.
